package com.vimaljha.retailpro

import android.Manifest
import android.app.*
import android.content.pm.PackageManager
import android.graphics.Color
import android.os.Bundle
import android.view.*
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import androidx.core.app.ActivityCompat
import com.google.zxing.integration.android.IntentIntegrator
import java.text.SimpleDateFormat
import java.util.*

class MainActivity: AppCompatActivity(){
 lateinit var db:RetailDb; lateinit var body:LinearLayout; val cart=mutableListOf<CartItem>(); var currentCustomer=0
 data class CartItem(var id:Long,var name:String,var barcode:String,var qty:Double,var unit:String,var rate:Double,var cost:Double)
 override fun onCreate(b:Bundle?){super.onCreate(b);db=RetailDb(this);buildShell();showDashboard()}
 fun buildShell(){
  val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(Color.rgb(244,247,251))}
  val bar=LinearLayout(this).apply{setPadding(22,18,22,18);setBackgroundColor(Color.rgb(16,24,40));gravity=Gravity.CENTER_VERTICAL}
  bar.addView(TextView(this).apply{text="RetailPro  •  Vimal Jha Kirana Shop";setTextColor(Color.WHITE);textSize=19f;setTypeface(null,1)},LinearLayout.LayoutParams(0,60,1f))
  root.addView(bar)
  val nav=LinearLayout(this).apply{setPadding(8,6,8,6);setBackgroundColor(Color.WHITE)}
  listOf("Dashboard","Billing","Inventory","Purchases","Customers","Suppliers").forEach{label->nav.addView(Button(this).apply{text=label;setOnClickListener{when(label){"Dashboard"->showDashboard();"Billing"->showBilling();"Inventory"->showInventory();"Purchases"->showPurchases();"Customers"->showCustomers();"Suppliers"->showSuppliers()}}},LinearLayout.LayoutParams(0,52,1f)))}
  root.addView(nav);body=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(16,12,16,24)};root.addView(ScrollView(this).apply{addView(body)},LinearLayout.LayoutParams(-1,0,1f));setContentView(root)
 }
 fun clear(title:String){body.removeAllViews();body.addView(TextView(this).apply{text=title;textSize=27f;setTextColor(Color.rgb(16,24,40));setTypeface(null,1);setPadding(4,8,4,16)})}
 fun tv(s:String,size:Float=15f,bold:Boolean=false)=TextView(this).apply{text=s;textSize=size;setTextColor(Color.rgb(31,41,55));if(bold)setTypeface(null,1);setPadding(4,7,4,7)}
 fun btn(s:String,click:()->Unit)=Button(this).apply{text=s;setOnClickListener{click()}}
 fun card(label:String,value:String):LinearLayout=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(16,12,16,12);setBackgroundColor(Color.WHITE);addView(tv(label,13f));addView(tv(value,23f,true));}
 fun showDashboard(){clear("Dashboard");val today=SimpleDateFormat("yyyy-MM-dd",Locale.US).format(Date());val sales=db.q("SELECT COALESCE(SUM(grand_total),0) s,COUNT(*) bills FROM sales WHERE date(created_at/1000,'unixepoch','localtime')=?",arrayOf(today));val pur=db.q("SELECT COALESCE(SUM(grand_total),0) p,COUNT(*) bills FROM purchases WHERE date(created_at/1000,'unixepoch','localtime')=?",arrayOf(today));val items=db.q("SELECT COALESCE(SUM(qty),0) q FROM sale_items si JOIN sales s ON s.id=si.sale_id WHERE date(s.created_at/1000,'unixepoch','localtime')=?",arrayOf(today));val g=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};g.addView(card("Today Sales","₹${fmt(sales.firstOrNull()?.get("s"))}"));g.addView(card("Bills Sold","${sales.firstOrNull()?.get("bills")?:0}"));g.addView(card("Items Sold","${items.firstOrNull()?.get("q")?:0}"));g.addView(card("Stock Purchase","₹${fmt(pur.firstOrNull()?.get("p"))}"));body.addView(g);body.addView(tv("Offline mode: all billing, inventory, purchases and customer data are stored on this phone.",14f))}
 fun showBilling(){clear("Billing / POS");val search=EditText(this).apply{hint="Search product name or barcode"};val row=LinearLayout(this);row.addView(search,LinearLayout.LayoutParams(0,60,1f));row.addView(btn("📷 Scan"){scan{code->search.setText(code);findAndAdd(code)}});body.addView(row);val result=LinearLayout(this);body.addView(result);val cust=Spinner(this);val names= mutableListOf("Walk-in Customer");db.q("SELECT id,name FROM customers ORDER BY name").forEach{names.add(it["name"].toString())};cust.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,names);body.addView(tv("Customer",13f,true));body.addView(cust);val pay=Spinner(this);pay.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,listOf("Cash","UPI","Card","Udhari"));body.addView(tv("Payment",13f,true));body.addView(pay);val disc=EditText(this).apply{hint="Discount";inputType=2};body.addView(disc);val cartBox=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};body.addView(cartBox);fun render(){cartBox.removeAllViews();var total=0.0;cart.forEachIndexed{i,x->val line=x.qty*x.rate;total+=line;cartBox.addView(tv("${i+1}. ${x.name}  •  ${num(x.qty)} ${x.unit}  × ₹${fmt(x.rate)}  = ₹${fmt(line)}",15f,true))};cartBox.addView(tv("${cart.sumOf{it.qty}.toInt()} items    GRAND TOTAL ₹${fmt(total-(disc.text.toString().toDoubleOrNull()?:0.0))}",19f,true))};search.setOnEditorActionListener{_,_,_->findAndAdd(search.text.toString());true};body.addView(btn("✓ Save Bill & Print"){saveSale(pay.selectedItem.toString(),disc.text.toString().toDoubleOrNull()?:0.0,cust.selectedItemPosition);render()});render()}
 fun findAndAdd(q:String){if(q.isBlank())return;val p=db.q("SELECT * FROM products WHERE barcode=? OR lower(name) LIKE lower(?) LIMIT 1",arrayOf(q,"%$q%"));if(p.isEmpty()){toast("Product not found");return};val r=p[0];val id=r["id"] as Long;val old=cart.find{it.id==id};if(old!=null)old.qty+=1 else cart.add(CartItem(id,r["name"].toString(),r["barcode"].toString(),1.0,r["unit"].toString(),(r["selling_price"] as Double),(r["purchase_price"] as Double)));showBilling()}
 fun saveSale(payment:String,discount:Double,custPos:Int){if(cart.isEmpty()){toast("Add product first");return};var sub=cart.sumOf{it.qty*it.rate};val grand=(sub-discount).coerceAtLeast(0.0);val paid=if(payment=="Udhari")0.0 else grand;val inv="INV-"+SimpleDateFormat("yyyyMMdd-HHmmss",Locale.US).format(Date());val sid=db.exec("INSERT INTO sales(invoice_no,customer_id,subtotal,discount,gst_total,grand_total,payment_method,paid_amount,created_at) VALUES(?,?,?,?,?,?,?,?,?)",arrayOf(inv,if(custPos==0)null else getCustomerId(custPos),sub,discount,0,grand,payment.lowercase(),paid,System.currentTimeMillis()/1000));cart.forEach{x->db.exec("INSERT INTO sale_items(sale_id,product_id,barcode,product_name,qty,unit,rate,gst_rate,gst_amount,line_total) VALUES(?,?,?,?,?,?,?,?,?,?)",arrayOf(sid,x.id,x.barcode,x.name,x.qty,x.unit,x.rate,0,0,x.qty*x.rate));db.exec("UPDATE products SET stock=stock-? WHERE id=?",arrayOf(x.qty,x.id))};if(custPos>0&&payment=="Udhari")db.exec("INSERT INTO ledger(party_type,party_id,reference_type,reference_id,debit,credit,note,created_at) VALUES('customer',?,?,?,?,?,?,?)",arrayOf(getCustomerId(custPos),"sale",sid,grand,0,"Udhari sale",System.currentTimeMillis()/1000));toast("Saved $inv");cart.clear()}
 fun getCustomerId(pos:Int):Long=(db.q("SELECT id FROM customers ORDER BY name LIMIT 1 OFFSET ?",arrayOf((pos-1).toString())).first()["id"] as Long)
 fun showInventory(){clear("Inventory");val search=EditText(this).apply{hint="Search name or barcode"};body.addView(search);body.addView(btn("📷 Scan Barcode"){scan{code->search.setText(code);renderProducts(code)}});val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};body.addView(list);fun render(q:String=""){list.removeAllViews();val rows=db.q("SELECT * FROM products WHERE name LIKE ? OR barcode LIKE ? ORDER BY name",arrayOf("%$q%","%$q%"));rows.forEachIndexed{i,r->list.addView(tv("${i+1}. ${r["name"]} | ${r["barcode"]} | ${num(r["stock"])} ${r["unit"]} | Sell ₹${fmt(r["selling_price"])}",15f,true))}};search.setOnEditorActionListener{_,_,_->render(search.text.toString());true};render()}
 fun renderProducts(q:String){val rows=db.q("SELECT * FROM products WHERE barcode=? LIMIT 1",arrayOf(q));toast(if(rows.isEmpty())"Product not found" else "Found: ${rows[0]["name"]}")}
 fun showPurchases(){clear("Bulk Purchases");val search=EditText(this).apply{hint="Search or scan barcode"};body.addView(search);body.addView(btn("📷 Scan & Add"){scan{code->addPurchaseProduct(code)}});body.addView(btn("＋ Add Product Manually"){addPurchaseDialog()});val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};body.addView(list);body.addView(btn("✓ Save Purchase"){toast("Purchase cart is stored locally in this offline version")})}
 fun addPurchaseProduct(code:String){val p=db.q("SELECT * FROM products WHERE barcode=? LIMIT 1",arrayOf(code));if(p.isEmpty()){toast("Product not found");return};val r=p[0];addPurchaseDialog(r)}
 fun addPurchaseDialog(p:MutableMap<String,Any?>?=null){val q=EditText(this).apply{hint="Quantity"};val rate=EditText(this).apply{hint="Purchase rate";setText(p?.get("purchase_price")?.toString() ?: "")};LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;padding();addView(q);addView(rate)}.also{box->AlertDialog.Builder(this).setTitle(p?.get("name")?.toString() ?: "Purchase item").setView(box).setPositiveButton("Add"){_,_->toast("Added to purchase cart")}.setNegativeButton("Cancel",null).show()}}
 fun showCustomers(){clear("Customers");val search=EditText(this).apply{hint="Search name or mobile"};body.addView(search);val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};body.addView(list);fun render(q:String=""){list.removeAllViews();db.q("SELECT c.*,COALESCE((SELECT SUM(s.grand_total) FROM sales s WHERE s.customer_id=c.id),0) purchase,COALESCE((SELECT SUM(l.debit-l.credit) FROM ledger l WHERE l.party_type='customer' AND l.party_id=c.id),0) due FROM customers c WHERE c.name LIKE ? OR c.phone LIKE ? ORDER BY c.name",arrayOf("%$q%","%$q%")).forEachIndexed{i,r->list.addView(tv("${i+1}. ${r["name"]} | ${r["phone"]} | Purchase ₹${fmt(r["purchase"])} | Udhari ₹${fmt(r["due"])}",15f,true))}};render();search.setOnEditorActionListener{_,_,_->render(search.text.toString());true}}
 fun showSuppliers(){clear("Suppliers");db.q("SELECT * FROM suppliers ORDER BY name").forEachIndexed{i,r->body.addView(tv("${i+1}. ${r["name"]} | ${r["phone"]}",16f,true))};body.addView(btn("＋ Add Supplier"){toast("Supplier form can be added in the next module update")})}
 fun scan(done:(String)->Unit){if(ActivityCompat.checkSelfPermission(this,Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){ActivityCompat.requestPermissions(this,arrayOf(Manifest.permission.CAMERA),22);return};IntentIntegrator(this).setPrompt("Scan 1D product barcode").setBeepEnabled(true).setOrientationLocked(false).initiateScan()};override fun onActivityResult(r:Int,c:Int,d:android.content.Intent?){super.onActivityResult(r,c,d);val res=IntentIntegrator.parseActivityResult(r,c,d);if(res?.contents!=null){pendingScan=res.contents;showScanResult()}}
 var pendingScan="";fun showScanResult(){toast("Scanned: $pendingScan");findAndAdd(pendingScan)}
 fun fmt(v:Any?):String=String.format(Locale.US,"%.2f",(v as? Number)?.toDouble()?:0.0);fun num(v:Any?):String=String.format(Locale.US,"%.3f",(v as? Number)?.toDouble()?:0.0);fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_SHORT).show();fun LinearLayout.padding(){setPadding(16,8,16,8)}
}
